name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: mandoof1
          outputs: |
            dist/snake.svg?color_snake=#58a6ff&color_dots=#161b22,#0e4429,#26a641,#3fb950,#bc8cff&color_background=#0d1117
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif?color_snake=#58a6ff&color_dots=#161b22,#0e4429,#26a641,#3fb950,#bc8cff
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
