name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: mandoof1
          outputs: |
            dist/snake.svg?color_snake=#c8ffd9&color_dots=#0f2e1a,#0aa832,#00ff41,#00d4ff,#ff0055&color_background=#0d1117&color_dot_border=#00ff4122
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
